services:
  catalogdb:
    image: postgres:16
    container_name: catalogdb
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CatalogDb

    ports:
      - "5432:5432"

    volumes:
      - postgres_catalog:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
    container_name: catalog.api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ConnectionStrings__Database: >
        Server=catalogdb;
        Port=5432;
        Database=catalogdb;
        User Id=postgres;
        Password=postgres;
        Include Error Detail=true
    depends_on:
      catalogdb:
        condition: service_healthy
    ports:
      - "6000:8080"

volumes:
  postgres_catalog:

